"""Add favorite player and team to model

Revision ID: 0059d2490008
Revises: 71e5859667c2
Create Date: 2020-04-12 13:06:55.369827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0059d2490008'
down_revision = '71e5859667c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('player', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('team', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_player'), 'user', ['player'], unique=True)
    op.create_index(op.f('ix_user_team'), 'user', ['team'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_team'), table_name='user')
    op.drop_index(op.f('ix_user_player'), table_name='user')
    op.drop_column('user', 'team')
    op.drop_column('user', 'player')
    # ### end Alembic commands ###
