"""Add secondary features

Revision ID: 0e45cfb3be54
Revises: 21627f1784ef
Create Date: 2020-04-18 23:16:36.931314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e45cfb3be54'
down_revision = '21627f1784ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('preferred_foot', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'preferred_foot')
    # ### end Alembic commands ###
