"""Add secondary attributes to player table

Revision ID: 21627f1784ef
Revises: 37be31cb1a37
Create Date: 2020-04-18 23:11:26.140226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21627f1784ef'
down_revision = '37be31cb1a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('overall', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('player_position', sa.String(length=128), nullable=True))
    op.add_column('player', sa.Column('potential', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('wage', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('weight', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_player_height'), 'player', ['height'], unique=False)
    op.create_index(op.f('ix_player_overall'), 'player', ['overall'], unique=False)
    op.create_index(op.f('ix_player_potential'), 'player', ['potential'], unique=False)
    op.create_index(op.f('ix_player_value'), 'player', ['value'], unique=False)
    op.create_index(op.f('ix_player_wage'), 'player', ['wage'], unique=False)
    op.create_index(op.f('ix_player_weight'), 'player', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_weight'), table_name='player')
    op.drop_index(op.f('ix_player_wage'), table_name='player')
    op.drop_index(op.f('ix_player_value'), table_name='player')
    op.drop_index(op.f('ix_player_potential'), table_name='player')
    op.drop_index(op.f('ix_player_overall'), table_name='player')
    op.drop_index(op.f('ix_player_height'), table_name='player')
    op.drop_column('player', 'weight')
    op.drop_column('player', 'wage')
    op.drop_column('player', 'value')
    op.drop_column('player', 'potential')
    op.drop_column('player', 'player_position')
    op.drop_column('player', 'overall')
    op.drop_column('player', 'height')
    # ### end Alembic commands ###
