"""Add player table

Revision ID: 27312de9c8c7
Revises: d52f95e9c547
Create Date: 2020-04-13 22:11:50.470695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27312de9c8c7'
down_revision = 'd52f95e9c547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('sofifa_id', sa.Integer(), nullable=False),
    sa.Column('club', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('long_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('sofifa_id')
    )
    op.create_index(op.f('ix_player_club'), 'player', ['club'], unique=False)
    op.create_index(op.f('ix_player_country'), 'player', ['country'], unique=False)
    op.create_index(op.f('ix_player_long_name'), 'player', ['long_name'], unique=True)
    op.create_index(op.f('ix_player_short_name'), 'player', ['short_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_short_name'), table_name='player')
    op.drop_index(op.f('ix_player_long_name'), table_name='player')
    op.drop_index(op.f('ix_player_country'), table_name='player')
    op.drop_index(op.f('ix_player_club'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
