"""Fix player and team fields in data model

Revision ID: d52f95e9c547
Revises: 0059d2490008
Create Date: 2020-04-12 13:19:41.092426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52f95e9c547'
down_revision = '0059d2490008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_player', table_name='user')
    op.drop_index('ix_user_team', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_team', 'user', ['team'], unique=1)
    op.create_index('ix_user_player', 'user', ['player'], unique=1)
    # ### end Alembic commands ###
